### ISSUE TITLE
[Documentation] "Invalid Equation" on Documentation Page

### ISSUE THREAD

**Issue by chaojian-zhang** [SpiceSharp/SpiceSharp#101]
Hi, on [Modified Nodal Analysis](https://spicesharp.github.io/SpiceSharp/articles/custom_components/modified_nodal_analysis.html) page there is a "**Invalid Equation**" below the line "_Kirchoff's Current Law states that the sum of all currents in every node has to equal zero. In this circuit, we have 3 nodes, and so we get a system of 3 equations:..._"

![2020-05-14 11 05 31](https://user-images.githubusercontent.com/7077098/81951208-e112d500-95d2-11ea-8e4c-6fbeded84851.png)

A similar issue happens on a later paragraph:

![2020-05-14 11 07 51](https://user-images.githubusercontent.com/7077098/81951526-3fd84e80-95d3-11ea-968e-26cf82bf14c6.png)

Thanks!

**Comment by svenboulanger** [comment]
There indeed seem to be some issues with some equations in the documentation. I will be rewriting most of the documentation for v3, so I'll include this with that release.

**Comment by svenboulanger** [comment]
This has been fixed!
