### ISSUE TITLE
AM Demodulation

### ISSUE THREAD

**Issue by ViacheslavMezentsev** [SpiceSharp/SpiceSharp#114]
Is it possible to simulate?

Or how to get AM Modulation?

![AM Modulated Signal (AM Modulation)](https://user-images.githubusercontent.com/942421/97404764-6a675b00-1918-11eb-8274-27684fd1887b.png)

**Comment by svenboulanger** [comment]
Hi, if you use `Spice#.Behavioral`, you can create a voltage source that multiples two other voltages. Perhaps you can try that?

**Comment by svenboulanger** [comment]
Starting at Spice# 3.1, the waveform "AM" is supported.

**Comment by ViacheslavMezentsev** [comment]
It works

<img width="706" height="754" alt="Image" src="https://github.com/user-attachments/assets/118d1baa-fdd6-4a35-aad3-4c7790800585" />
