### ISSUE TITLE
Initial conditions are not considered for calculating the Operation Point

### ISSUE THREAD

**Issue by jaminSch** [SpiceSharp/SpiceSharp#124]
Hello, I've got a question about how Preconditions are considered for the Operation Point.

If I give my capacitor in a simple circuit (Voltage Source with Pulse, Resistor, Capacitor) a Precondition of 4.0 Volt and set the simulation.TimeParameter.UseIc flag on true in my understanding the precondition should be considered or am I missing something? What happens in the Code is following:

Simulation.Run() -> Execute() ->

![UseIc_UseDC_Set](https://user-images.githubusercontent.com/57145245/99650943-4f3ec580-2a56-11eb-9725-b709cdcf6ac5.PNG)
Before calculating the operation Point it is set that the Preconditions should be considered (Debugging showed that the value _time.UseIc = true in my case).

![CapacitorBehavior](https://user-images.githubusercontent.com/57145245/99652272-e9533d80-2a57-11eb-968c-d5319c549d5f.PNG)
While Loading the Behaviors the capacitor is ignored because of the DC Analysis and the UseIc-flag is not considered.

![UseIcReset](https://user-images.githubusercontent.com/57145245/99652445-21f31700-2a58-11eb-8af0-70f412f4ff78.PNG)
After finding the Operationpoint without considering the preconditions the flag saying Preconditions should be considered is reset and the InitializeStates() Method is called.

![InitializeStates](https://user-images.githubusercontent.com/57145245/99652652-6088d180-2a58-11eb-89a1-7148afb73c0e.PNG)
During this initialization preconditions would be considered if the flag wasnt reset before.

Thank you for your help and for sharing the code it really helps me understanding the computer based analysis of electronic circuits!

**Comment by svenboulanger** [comment]
Hi,

Spice has a pretty (in my opinion) confusing way of handling initial conditions. I believe that what you did was specify an initial condition on the capacitor, while in fact you probably need to specify an initial condition on the node.

Check [this example](https://github.com/SpiceSharp/SpiceSharp/blob/4b684a7f60e1aebaa0c41270620e151fa7614906/SpiceSharpTest/Simulations/TransientTests.cs#L132) to see how a "floating node" can be fixed using initial conditions.

Another - less used - alternative way of using initial conditions is using the `UseIc` flag which should skip any DC analysis and will instead use the "ic"-parameters specified on all devices. For example, diodes and BJT's have "ic"-parameters, just like a capacitor.
I don't think the latter feature is tested as it is (from experience) an uncommon thing to use. I may add some tests to be sure in the future.

**Comment by jaminSch** [comment]
Hi,
thank you for your help!
I tried your example and it works.

I am still wondering why there is an option to initialize the capacitor when it doesnt change its behavior.
In my last picture you can see the ITimeBehavior.InitializeStates-Method in which the Initial Conditions of the Capacitor are considered if the UseIc flag is set (which is hard reset right before the method call (Picture 3)).

I actually think the UseIc flag doesnt stop the DC analysis as you can see in my code snippets (Picture 1) above, the UseDC flag is set to true  independently of the UseIc flag. 

The topic can still be considered "closed" i guess because your solution with initializing the node does work!

**Comment by svenboulanger** [comment]
Thanks for checking!

I think this would be a good time to take a look at the `UseIc` behavior and write some tests and possibly fix the bugs if it doesn't work as expected. I'll leave this issue open for now.

**Comment by svenboulanger** [comment]
I've given the UIC behavior an overhaul, but it still needs tests to make sure everything operates as expected. I would like to keep this issue open for a little longer to make sure I add some tests.
