### ISSUE TITLE
Validation of TemperatureCelsius property in SpiceSharp.Components.JFETs.Parameters class

### ISSUE THREAD

**Issue by marcin-golebiowski** [SpiceSharp/SpiceSharp#154]
I'm not sure about validation that is here:
![image](https://user-images.githubusercontent.com/115426/114731113-c21c4600-9d41-11eb-89a3-339ddbe0e278.png)

Why temperature in celsius must be greater than Constants.CelsiusKelvin ?

**Comment by svenboulanger** [comment]
That is a mistake. It's supposed to be greater than `-Constants.CelsiusKelvin`. The Units is in degrees celsius, the unicode is for the 'degree' character.
