### ISSUE TITLE
Question: Can we use this in Unity?

### ISSUE THREAD

**Issue by AzadKshitij** [SpiceSharp/SpiceSharp#166]
I have tried importing this in unity but it was giving some error is there any way to use this in unity??

**Comment by svenboulanger** [comment]
Which version have you tried and how does it fail?
It should target .NET standard 2.0, and I thought Unity supported that.

**Comment by AzadKshitij** [comment]
Yes I used another method by downloading package from nuget and using DLL file in my unity project and it worked BTW thanks for this awesome repo. We are making Circuit simulator game for students using unity  and your documentation is very helpful❤.
