### ISSUE TITLE
Voltage across diodes does not work as expected

### ISSUE THREAD

**Issue by LarsSem** [SpiceSharp/SpiceSharp#169]
Hello, I have some problems with the diodes. 
My goal is to get the voltage across the diode, but it is 0 all the time. I was expecting something like voltage2. I also tried the same export with a resistor that works as expected. 
This is the same case with the current.

        var dModel = new DiodeModel("test");

        var ckt = new Circuit(
            new VoltageSource("V1", "a", "0", 0),
            new Resistor("R1", "b", "0", 1000),
            new Diode("LED","a" ,"b" , "test"),
            dModel
            );

        var dc = new DC("DC", "V1", -3.0, 3.0, 0.1);

        var voltageExport = new RealPropertyExport(dc, "LED", "v");

        dc.ExportSimulationData += (sender, args) =>
        {
            var voltage = voltageExport.Value;

            var voltage2 = args.GetVoltage("a")- args.GetVoltage("b");

        };
        dc.Run(ckt);

Thanks for your help, i really appreciate this project

**Comment by svenboulanger** [comment]
With reflection having been removed, I forgot to add the attribute that activates the source generator for properties. It will be fixed with the next update.
