### ISSUE TITLE
CVD model for zener diode?

### ISSUE THREAD

**Issue by AzadKshitij** [SpiceSharp/SpiceSharp#199]
How can i make CVD model for zener diode??

**Comment by svenboulanger** [comment]
Well, I think you might be best off combining a voltage-controlled switch with a voltage source (I'm assuming you mean a "constant voltage drop" model).

If you connect the control terminals of the switch to its own terminals, you basically have an idealized one-way switch. The voltage source in series is just the voltage drop you want to model.
