### ISSUE TITLE
Getting started circuit diagram shows other values than code sample

### ISSUE THREAD

**Issue by cdsenselab** [SpiceSharp/SpiceSharp#220]
Hi!

I just noticed a typo in the circuit diagram in the getting started docs (https://spicesharp.github.io/SpiceSharp/articles/tutorials/gettingstarted.html). I was confused how to get 2/3 voltage using this setup. The diagram shows two 10 kOhm resistors, but the code sample describes a 10 kOhm and a 20 kOhm resistor. 

Best,
    Claus

**Comment by svenboulanger** [comment]
You're right, the diagram is supposed to show a 20kOhm resistor. I'll make the change.
