### ISSUE TITLE
Parallel test not running in parallel

### ISSUE THREAD

**Issue by sudsy** [SpiceSharp/SpiceSharp#224]
Seems like the following line in the parallel tests folder is not really running in parallel. Seems like it should reference IBiasingBehavior rather than IBiasingSimulation. 

https://github.com/SpiceSharp/SpiceSharp/blob/cd6430e9ef8b17d42aaa102a6b70ebf1def35576/SpiceSharpTest/Models/Parallel/SimpleParallelTests.cs#L24

**Comment by svenboulanger** [comment]
Thanks! I'll take a look when I find the time.
