### ISSUE TITLE
Singular matrix exception in MarkowitzEntireMatrix.FindPivot when DC simulating simple circuit

### ISSUE THREAD

**Issue by Nemeritz** [SpiceSharp/SpiceSharp#34]
Hello Sven,

I am trying to run a simple dc simulation with the following code which is pretty similar to the examples from the getting started page.

`        
        Circuit ckt = new Circuit();

        ckt.Objects.Add(new Resistor("R1", "1", "2", 100.0));
        ckt.Objects.Add(new Resistor("R2", "2", "3", 100.0));
        ckt.Objects.Add(new Resistor("R3", "2", "3", 100.0));
        ckt.Objects.Add(new VoltageSource("V1", "3", "1", 5));
        DC dc = new DC("DC sim", "V1", 4, 5, 1);

        dc.OnExportSimulationData += (sender, args) =>
        {
            for (int i = 1; i < 4; i++)
            {
                  Debug.Log(args.GetVoltage(i.ToString()));
            }
        };
        dc.Run(ckt);
`

But the following exception is thrown in the MarkowitzEntireMatrix.FindPivot function. I don't really what the function does so its hard for me to debug what's wrong. Just wondering if I set up the circuit wrong or is there something else which could be wrong?

```

Exception thrown: 'SpiceSharp.Algebra.SingularException' in SpiceSharp.dll
'ar-spicybread.exe' (CoreCLR: CoreCLR_UWP_Domain): 

Loaded 'C:\Data\Users\DefaultAccount\AppData\Local\DevelopmentFiles\ARSpicyBreadVS.Debug_x86.Pat\System.Diagnostics.StackTrace.dll'. Cannot find or open the PDB file.
SingularException: Singular matrix

   at SpiceSharp.Algebra.Solve.MarkowitzEntireMatrix1.FindPivot(Markowitz1 markowitz, SparseMatrix1 matrix, Int32 eliminationStep)

   at SpiceSharp.Algebra.Solve.Markowitz1.FindPivot(SparseMatrix1 matrix, Int32 eliminationStep)

   at SpiceSharp.Algebra.RealSolver.OrderAndFactor()

   at SpiceSharp.Simulations.BaseSimulation.Iterate(Int32 maxIterations)

   at SpiceSharp.Simulations.DC.Execute()

   at SpiceSharp.Simulations.Simulation.Run(Circuit circuit, SimulationFlowController controller)

   at SpiceSharp.Simulations.Simulation.Run(Circuit circuit)


```
Thanks for the help :)

**Comment by marcin-golebiowski** [comment]
There must be a ground node in a circuit ("0", "gnd", "GND")

Try:
![image](https://user-images.githubusercontent.com/115426/43083831-b24c2b34-8e97-11e8-8fcb-7ebec6d8c643.png)

**Comment by marcin-golebiowski** [comment]
There must be a ground node ("0", "GND", "gnd")

![image](https://user-images.githubusercontent.com/115426/43083987-0b6ede00-8e98-11e8-8c88-ee825fa2fa24.png)

**Comment by marcin-golebiowski** [comment]
You can run: ckt.Validate() to validate your circuit.

**Comment by svenboulanger** [comment]
These type of exceptions are thrown when the circuit can't be solved. In your example, like @marcin-golebiowski said, the simulator can't assign absolute voltages to each node, because it is not referenced anywhere to ground. There are infinitely many solutions to this problem, and so the circuit cannot be solved by the simulator.

**Comment by Nemeritz** [comment]
Thanks for the help, I didn't know about that. My code before used to automatically generate 0's so I didn't run into this problem before. Also thanks for the tip, Validate seems very useful.
