### ISSUE TITLE
Documentation update

### ISSUE THREAD

**Issue by majdaneq** [SpiceSharp/SpiceSharp#44]
Hello, 
could you please update the documentation file? 
It would be useful for new users of your project.

Regards,
Simon

**Comment by svenboulanger** [comment]
Certainly! Do you have any specific requests (other than regenerating the API documentation)?

**Comment by majdaneq** [comment]
Yes, thank you from the bottom of my heart!

**Comment by hoanpt88** [comment]
yes, thank you very much !!
