### ISSUE TITLE
FrequencyBehavior for VoltageSource

### ISSUE THREAD

**Issue by marcin-golebiowski** [SpiceSharp/SpiceSharp#50]
The AC excitation vector is computed in Setup. That prevents the parser from updating acmagnitude or acphase. Please consider moving following code to `Load` of the FrequencyBehavior:

            var radians = _ap.AcPhase * Math.PI / 180.0;
            Ac = new Complex(_ap.AcMagnitude * Math.Cos(radians), _ap.AcMagnitude * Math.Sin(radians));

**Comment by svenboulanger** [comment]
Good point. But I think the most logical place would be in the base parameters (CalculateDefaults) or a property there.

I'll fix it later.
