### ISSUE TITLE
Inductor current

### ISSUE THREAD

**Issue by marcin-golebiowski** [SpiceSharp/SpiceSharp#57]
Could you please verify if an inductor current getter is properly implemented ?
I think that maybe instead of `flux` name there  should be there `i`.

![image](https://user-images.githubusercontent.com/115426/48342871-24545680-e671-11e8-877a-15112a7f2907.png)

**Comment by svenboulanger** [comment]
That is because it hasn't been defined yet. The components are currently under revision. It will be added in the next update.
