### ISSUE TITLE
Small bug in BehaviorPool class

### ISSUE THREAD

**Issue by marcin-golebiowski** [SpiceSharp/SpiceSharp#75]
The parameter `comparer` is unused. 

![image](https://user-images.githubusercontent.com/115426/55195306-6ad3c900-51ac-11e9-9cfc-e510d4c0d755.png)

**Comment by svenboulanger** [comment]
Will be fixed in the next update. Thanks.

**Comment by marcin-golebiowski** [comment]
I have almost everything ready for release of SpiceSharpParser. I have only 1 test failing because of this small bug in SpiceSharp. But it somehow important.  
Could you kindly release of 2.6.1 so  I can publish new SpiceSharpParser ?

**Comment by svenboulanger** [comment]
I have uploaded v2.6.1. It will be available as soon as it is validated and indexed on NuGet.

**Comment by marcin-golebiowski** [comment]
Thank you very much.
