### ISSUE TITLE
Unstable tests in Spice#.Parser

### ISSUE THREAD

**Issue by marcin-golebiowski** [SpiceSharp/SpiceSharp#81]
After update to SpiceSharp 2.7 the integration tests are unstable.
There is a following error:
![image](https://user-images.githubusercontent.com/115426/60612709-98429b00-9dc9-11e9-9e78-3a55d6facb34.png)

**Comment by svenboulanger** [comment]
What are the inputs to `SetParameter<T>()` and what type `T` are you using?

**Comment by marcin-golebiowski** [comment]
Parameter<double> i think

**Comment by svenboulanger** [comment]
It turns out that there's no proper read/write lock for the caching system in `ParameterHelper`. So when multiple threads try to access the cache, it can give errors. I'll fix it soon.
