### ISSUE TITLE
Postprocessing data (Alternative to .MEASURE)

### ISSUE THREAD

**Issue by ma-laforge** [SpiceSharp/SpiceSharp#90]
Hi, this is not really an issue, just the easiest way to contact you (hope that's ok).

I have tools to post process simulation results, if you need them:
 - Read in SPICE data files.
 - Collect data from multi-dimensional parametric sweeps into single variable.
 - Operate on multi-dim data using simple expressions.
 - Use expressions that are easier to write than Matlab code.
 - Automatic interpolation: Operate seamlessly on results from 2 different simulation runs (different time steps).
 - Look at results with a fast, interactive plotting tool.
   - Add H/V, and "Delta" markers to mark/measure points of interest.
   - Create high-quality .SVG/PNG/... outputs for design reviews.

### Links
 - **MDDatasets:** https://github.com/ma-laforge/MDDatasets.jl
 - **InspectDR:** https://github.com/ma-laforge/InspectDR.jl

NOTE: These tools are written in Julia.  Julia is a FREE, MIT-conceived language that is fast, and EXTREMELY mathematically oriented.  It has the ease of use of MATLAB & Python, speeds approaching C, and many LISP influences.  Julia is very well constructed: it does NOT have the unpolished feel of most open-source tools I have used (ex: gnu-octave).

### Comparison to `.MEASURE`
Most simulators require you to re-simulate if you decide to modify `.MEASURE` statements (part of the netlist).

Instead, with MDDatasets, you should save all nodes of interest and POST-process the simulation results.  This allows you to only re-run derived calculations instead of having to re-simulate the circuit itself.

### Use in Conjunction with `.MEASURE`
Note that you could still compute results of interest using `.MEASURE` statements, then load/plot them with `MDDatasets.jl`/`InspectDR.jl` if you prefer.

**Comment by svenboulanger** [comment]
It would be less useful to me as I like to work within the VS/C# environment, but I appreciate the related interest on these topics.

It's not really an issue, like you said, so I'd like to close this.
