### ISSUE TITLE
Support for M, N parameters for capacitor, diode, resistor, inductor etc.

### ISSUE THREAD

**Issue by marcin-golebiowski** [SpiceSharp/SpiceSharp#94]
I would like to kindly ask for adding support for m,n parameters.
They are about number of parallel and series units of particular component.

**Comment by svenboulanger** [comment]
On which components do you want them?

**Comment by marcin-golebiowski** [comment]
Capacitor, diode, resistor, inductor.

Same as in LTSpice.
